language: ruby
cache: bundler
rvm:
  - 2.2.2

install:
  - pip install --user awscli

script:
  - bundle exec jekyll build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "eu-west-1"
    bucket: next.snowplowanalytics.com
    local-dir: new_site
    cache_control: "max-age=0"
    skip_cleanup: true
    on:
      branch: develop

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "eu-west-1"
    bucket: snowplowanalytics.com
    local-dir: new_site
    cache_control: "max-age=21600"
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  - aws configure set preview.cloudfront true
  - if [[ $TRAVIS_BRANCH == "master" ]]; then aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"; fi
